/* 修改 raw\*.txt 以通過文法展開 */


export const rawpatches={
    'dn1_168-4':[["natthi","na,atthi",6]],
    'dn1_171-2':[["naatthi","na atthi"],["natthi","na,atthi",9]],
     ['dn1_242-3']:[
        ["vītarāgaṃ","vīta rāgaṃ",2]
    ],
    'sn2_150-9':[["natthi","na,atthi",4]],
    'sn3_212-7':[["natthi","na,atthi",3]],
}

export const reuselemmadecomp={//同上中  沒有被展開的長詞
    'appekacce':['api','ekacce'],
    'kūṭāgāre':['kūṭa','agāre'],
    'yepissa':['ye','pi','assa'],
    'pādāpi':['pāde','api'],
    'nānantavā':['na','antavā'],   
    'nātikkameyyaṃ':['na','atikkameyyaṃ'],
    'nādhimuccati':['na','adhimuccati'],
    'yogakkhemaṃ':['yoga','khemaṃ'],
    'khomha':['kho','amha'],
    'khosmi':['kho','asmi'],
    'lokānukampāya':['loka','anukampāya'],
    'attāyaṃ':['attā','ayaṃ'],
    'aggodakaṃ':['agga','udakaṃ'],
    'yaññatthāya':['yañña','atthāya'],
    'khīṇāsavo':['khīṇa','āsavo'],
    'ceva':['ca','eva'],
    'mahābhitāpā':['mahā','abhitāpā'],
    'ayokhilaṃ':['ayo','khīlaṃ'],
    'pāramippatto':['pārami','patto'],
    'natthi':['na','atthi'],
    'tenevantaravassena':['tena','eva','antara','vassena'],
    'ākiñcaññāyatana':['ākiñcañña','āyatana'],
    'ākiñcaññāyatanasaññā':['ākiñcañña','āyatana','saññā'],
    'paramānuttaraṃ':['parama','anuttaraṃ'],
    'kkhandhena':['khandhena'],
    'appekaccāni':['api','ekaccāni'],
    'nāssuḷārāya':['na','assu','uḷārāya'],
    'mittāmacce':['mitta','amacce'],
    'kolaṭṭhi':['kola','aṭṭhi'],
    'kolaṭṭhimattiyo':['kola','aṭṭhi','mattiyo'],
    'sakkohaṃ':['sakko','ahaṃ'],
    'teva':['te','eva'],
    'nappajānanti':['na','pajānanti'],
    'vīriyārambhassa':['vīriya','ārambhassa'],
    'atītamaddhāna':['atīta','addhāna'],
    'piṇḍapātasenāsana':['piṇḍapāta','sena','āsana'],
    'gilānappaccaya':['gilāna','paccaya'],
    'kulūpako':['kula','upako'],
    'nappajānāti':['na','pajānāti'],
    'pissa':['pi','assa'],
    'anāgatamaddhāna':['anāgatam','addhānaṃ'],
    'tālāvatthukato':['tāla','avatthu','kato'],
    'dhammānusārī':['dhamma','anusārī'],
    'saddhānusārī':['saddhā','anusārī'],
    'cakkhundriya':['cakkhu','indriya'],
    'saddhindriya':['saddhā','indriyaṃ'],
    'dhammānupassī':['dhamma','anupassī'],
    'samādhippadhānasaṅkhārasamannāgataṃ':['samādhi','padhāna','saṅkhāra','samannāgataṃ'],
    'chandasamādhippadhānasaṅkhārasamannāgataṃ':['chanda','samādhi','padhāna','saṅkhāra','samannāgataṃ'],
    'sokaparidevadukkhadomanassupāyāsa':['soka','parideva','dukkha','domanassa','upāyāsa'],
    'ānāpānassatisahagataṃ':['ānāpāna','sati','sahagataṃ'],
    'bhāvanāparipūriṃ':['bhāvanā','pāripūriṃ'],
    'kammaphalūpajīvī':['kamma','phala','upajīvī'],
    'uṭṭhānaphalūpajīvī':['uṭṭhāna','phala','upajīvī'],
    'pārisuddhipadhāniyaṅgena':['pārisuddhi','padhāniya','aṅgena'],
    'yampissa':['yam','pi','assa'],
    'tampissa':['tam','pi','assa'],
    'sopissa':['so','pi','assa'],
    'yācitova':['yācito','eva'],
    'satova':['sato','eva'],
    'tibbacchando':['tibba','chando'],
    'khomhi':['kho','amhi'],
    'viññāṇañcāyatane':['viññāṇañca','āyatane'],
    'nevasaññānāsaññāyatanaṃ':['na','eva','saññā','na','asañña','āyatanaṃ'],
    'nevasaññānāsaññāyatane':['na','eva','saññā','na','asañña','āyatane'],
    'viññāṇañcāyatanam':['viññāṇañca','āyatanam'],
    'viññāṇañcāyatanaṃ':['viññāṇañca','āyatanaṃ'],
    'ākiñcaññāyatanaṃ':['ākiñcañña','āyatanaṃ'],
    'ākiñcaññāyatanam':['ākiñcañña','āyatanam'],
    'ākāsānañcāyatanam':['ākāsānañca','āyatanam'],
    'ākāsānañcāyatanasaññā':['ākāsānañca','āyatana','saññā'],
    'viññāṇañcāyatanasaññā':['viññāṇañca','āyatana','saññā'],
    'nevasaññānāsaññāyatanasaññā':['na','eva','saññā','na','asañña','āyatana','saññā'],
    'sammāsamādhimhi':['sammā','samādhimhi'],
    'ākāsānañcāyatanaṃ':['ākāsānañca','āyatanaṃ'],
    'nevasaññānāsaññāyatanam':['na','eva','saññā','na','asañña','āyatanam'],
    'yampidaṃ':['yam','pi','idaṃ'],
    'saṅkhāyekaṃ':['saṅkhāya','ekaṃ'],
    'nālamariya':['na','alam','ariya'],
    'nālamariyā':['na','alam','ariyā'],
    'hemajālappaṭicchannāni':['hema','jāla','paṭicchannāni'],
    'sovaṇṇālaṅkārāni':['sovaṇṇa','alaṅkārāni'],
    'purisājānīye':['purisa','ājānīye']  ,
    'appeva':['api','eva'],

    'nāmāhaṃ':['nāma','ahaṃ'],
    'upaṭṭhitassatī':['upaṭṭhita','sati'],
    'upaṭṭhitassati':['upaṭṭhita','sati'],
    'nippapañcārāmo':['nippapañca','ārāmo'],
 
    'mittāmaccānaṃ':['mitta','amaccānaṃ'],
    'kappessasī':['kappessasi'],
    'vīriyārambhe':['vīriya','ārambhe'],
    'thūṇūpanītāni':['thūṇa','upanītāni'],
    'yaññatthāyā':['yañña','atthāya'],
    'dhammānudhammappaṭipanno':['dhamma','anudhamma','paṭipanno'],
    'tālamattam':['tāla','mattam'],
    'panekaccassa':['pana','ekaccassa']
}